version: "3.8"
services:

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  go-todo:
    build:
      context: .
    image: maxweis/go-todo-demo:v1.0
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres