version: "3.8"
services:

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  go-todo:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres